import { Component, OnInit } from '@angular/core';
import { User } from '../../models/user.model';
import { FlashMessagesService } from 'angular2-flash-messages';
import { RouterModule, Routes, NavigationExtras, Router, ActivatedRoute, ActivatedRouteSnapshot } from '@angular/router';
import { UserService } from '../../services/user.service';
import { NgForm, FormControl, FormBuilder,
    FormGroup, FormArray, Validators, AbstractControl, ValidatorFn } from '@angular/forms';
import { Reset } from '../../models/reset.model';
import { LoomNotificationsService } from '../../services/loom.notifications.service';
import { LoomNotification } from '../../models/loom.notification.model';

@Component({
    moduleId: module.id,
    templateUrl: 'reset.component.html',
    styleUrls: ['reset.component.css']
})

export class ResetComponent implements OnInit {
    model = <User> {};
    loading = false;
    error = '';
    message: string;
    resetForm: FormGroup;
    resetObject: Reset;
    resetKey: string;

    constructor(
        private userService: UserService,
        private _flashMessagesService: FlashMessagesService,
        private _router: Router,
        private formBuilder: FormBuilder,
        private _activatedRoute: ActivatedRoute,
        private _notes: LoomNotificationsService
         ) { }


    ngOnInit() {
        // Get the reset key from the url that was generated by the API and sent to the user via email
        // as verification that they are the one who requested the reset

        this.resetKey = this._activatedRoute.snapshot.params['key'];

        console.log( ' This reset key == ' + this.resetKey );


        this.resetForm = this.formBuilder.group( {
            email: [ '' , [ Validators.required ] ],
            password: ['', [ Validators.required ] ],
            password_confirmation: ['', [ Validators.required ]] });
    }

    sendReset() {
        // Complete the circle - but sending this reset request BACK to the API

        // put this var into an object so we can combine it with the form data
        const keyObject = { 'resetKey': this.resetKey };

         // This is Deborah Korata's way of merging our data model with the form model
        const combinedObject = Object.assign( {}, keyObject, this.resetForm.value);

        console.log('The combined object: ' + JSON.stringify(combinedObject) );

        this.userService
          .resetPassword( combinedObject ).subscribe(
          (err) => {
            console.log('POST call error ', err);
          },
          () => {
            console.log('The POST observable is now completed.');
            this._notes.add(
                new LoomNotification('success', ['Your password has now been reset.'], 10000));
            this._router.navigate(['/login']);
            }
          );
    }

}

